name: godiddy-cli

volumes:
  godiddy-cli-storage:

services:
  godiddy-cli:
    image: godiddy/godiddy-cli:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - godiddy-cli-storage:/opt/godiddy-cli/godiddy-cli-storage
