name: did-cli

volumes:
  did-cli-storage:

services:
  did-cli:
    image: godiddy/did-cli:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - did-cli-storage:/opt/did-cli/did-cli-storage
