name: Latest Deb Package

on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        required: false
        type: string
        default: '21'
        description: 'Java version to use for build'
    secrets:
      VAULT_ADDR:
        required: true
      CI_SECRET_READER_PERIODIC_TOKEN:
        required: true
      VAULTCA:
        required: true
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.JAVA_VERSION }}

      - name: Get current date for version
        id: date
        run: echo "CURRENT_DATE=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: Set latest version
        run: echo "VERSION=latest-${{ env.CURRENT_DATE }}" >> $GITHUB_ENV

      - name: Fetch Vault Secrets
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ secrets.VAULT_ADDR }}
          token: ${{ secrets.CI_SECRET_READER_PERIODIC_TOKEN }}
          caCertificate: ${{ secrets.VAULTCA }}
          secrets: |
            ci/data/gh-workflows/maven-danubetech-nexus username | MAVEN_USERNAME ;
            ci/data/gh-workflows/maven-danubetech-nexus password | MAVEN_PASSWORD

      - name: Configure Maven Settings
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml << 'EOF'
          <settings>
            <servers>
              <server>
                <id>danubetech-maven-snapshots</id>
                <username>${{ env.MAVEN_USERNAME }}</username>
                <password>${{ env.MAVEN_PASSWORD }}</password>
              </server>
              <server>
                <id>danubetech-maven-releases</id>
                <username>${{ env.MAVEN_USERNAME }}</username>
                <password>${{ env.MAVEN_PASSWORD }}</password>
              </server>
              <server>
                <id>danubetech-maven-internal</id>
                <username>${{ env.MAVEN_USERNAME }}</username>
                <password>${{ env.MAVEN_PASSWORD }}</password>
              </server>
              <server>
                <id>danubetech-maven-internal-releases</id>
                <username>${{ env.MAVEN_USERNAME }}</username>
                <password>${{ env.MAVEN_PASSWORD }}</password>
              </server>
              <server>
                <id>danubetech-maven-internal-snapshots</id>
                <username>${{ env.MAVEN_USERNAME }}</username>
                <password>${{ env.MAVEN_PASSWORD }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build with Maven
        run: mvn clean package

      - name: Install required dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot

      - name: Make packaging script executable
        run: |
          chmod +x ./godiddy-cli-package.sh

      - name: Package using bash script
        run: |
          ./godiddy-cli-package.sh --version ${{ env.VERSION }} --java-version ${{ inputs.JAVA_VERSION }} --compress 9
          # Move the output file to the expected location for the GitHub release
          mkdir -p build/output
          cp build/output/godiddy-cli_${{ env.VERSION }}_amd64.deb ./godiddy-cli_${{ env.VERSION }}_amd64.deb

      - name: Delete existing latest release
        run: |
          gh release delete latest --cleanup-tag --yes || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create or update latest tag
        run: |
          git tag -f latest
          git push origin latest -f

      - name: Create/Update Latest Release
        run: |
          # Create release notes
          echo "This is the latest build from the main branch." > release_notes.md
          echo "Build date: ${{ env.CURRENT_DATE }}" >> release_notes.md
          echo "" >> release_notes.md
          echo "⚠️ This is an unstable development build and may contain bugs." >> release_notes.md
          
          # Create the release with GitHub CLI
          gh release create latest \
            --title "Latest Build" \
            --notes-file release_notes.md \
            --prerelease \
            godiddy-cli_${{ env.VERSION }}_amd64.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Slack notification
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}