name: Docker latest image

on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - 'LICENSE'
      - 'docs'
    branches: [ main ]
  workflow_dispatch:

jobs:

  docker-latest:
    uses: danubetech/workflows/.github/workflows/docker-latest.yml@main
    with:
      GLOBAL_IMAGE_NAME: godiddy/godiddy-cli
      GLOBAL_REPO_NAME: docker.io
      PATH_TO_DOCKERFILE: docker/Dockerfile
    secrets:
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      CI_SECRET_READER_PERIODIC_TOKEN: ${{ secrets.CI_SECRET_READER_PERIODIC_TOKEN }}
      VAULTCA: ${{ secrets.VAULTCA }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  release-deb-package:
    needs: [ docker-latest ]
    runs-on: ubuntu-latest
    steps:
      - name: Latest deb package
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'latest-deb-package',
              ref: 'main'
            })
