name: Latest application

on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - 'LICENSE'
      - 'docs'
    branches: [ main ]
  workflow_dispatch:

jobs:

  docker-latest:
    uses: danubetech/workflows/.github/workflows/docker-latest.yml@main
    with:
      GLOBAL_IMAGE_NAME: godiddy/godiddy-cli
      GLOBAL_REPO_NAME: docker.io
      PATH_TO_DOCKERFILE: docker/Dockerfile
    secrets:
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      CI_SECRET_READER_PERIODIC_TOKEN: ${{ secrets.CI_SECRET_READER_PERIODIC_TOKEN }}
      VAULTCA: ${{ secrets.VAULTCA }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  latest-deb-package:
    needs: [ docker-latest ]
    uses: danubetech/godiddy-cli/.github/workflows/latest-deb-package.yml@fix-package-workflow
    secrets:
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      CI_SECRET_READER_PERIODIC_TOKEN: ${{ secrets.CI_SECRET_READER_PERIODIC_TOKEN }}
      VAULTCA: ${{ secrets.VAULTCA }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
