name: Release application

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Major, Minor or Patch release'
        type: choice
        required: true
        default: 'minor'
        options:
          - "major"
          - "minor"
          - "patch"

jobs:

  docker-release:
    uses: danubetech/workflows/.github/workflows/docker-release.yml@main
    with:
      GLOBAL_IMAGE_NAME: godiddy/godiddy-cli
      GLOBAL_REPO_NAME: docker.io
      GLOBAL_FRAMEWORK: maven
      PATH_TO_DOCKERFILE: docker/Dockerfile
    secrets:
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      CI_SECRET_READER_PERIODIC_TOKEN: ${{ secrets.CI_SECRET_READER_PERIODIC_TOKEN }}
      VAULTCA: ${{ secrets.VAULTCA }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  release-deb-package:
    needs: [ docker-release ]
    uses: danubetech/godiddy-cli/.github/workflows/release-deb-package.yml@main
    secrets:
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      CI_SECRET_READER_PERIODIC_TOKEN: ${{ secrets.CI_SECRET_READER_PERIODIC_TOKEN }}
      VAULTCA: ${{ secrets.VAULTCA }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}